[project]
name = "logo-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.31.0",
    "pre-commit>=4.3.0",
    "python-dotenv>=1.1.1",
]
